name: Sync Private to Public Repo

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to public repository
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git clone https://${{ secrets.GIT_TOKEN }}@github.com/KnowledgeFound/Coding4Integrity-DeComm-Hackathon.git
          cd Coding4Integrity-DeComm-Hackathon
          git remote add DeComm https://${{ secrets.GIT_TOKEN }}@github.com/KnowledgeFound/DeComm.git
          git remote update
          git merge DeComm/master
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}