name: Sync to Public DeComm Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to public repo
        env:
          PUBLIC_REPO: "KnowledgeFound/Coding4Integrity-DeComm-Hackathon.git"
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote add public https://${GITHUB_ACTOR}:${GIT_TOKEN}@${PUBLIC_REPO}
          git push public HEAD:main --force